from kedro.pipeline import Pipeline, node

from .nodes import vocsedici_extract_tables


def create_pipeline(**kwargs) -> Pipeline:
    return Pipeline(
        [
            node(
                name="vocsedici_extract_tables",
                func=vocsedici_extract_tables,
                inputs=[
                    "params:vocsedici_extract_options.tables",
                    "params:vocsedici_extract_options.source_label",
                    "params:vocsedici_extract_options.env",
                    "params:vocsedici_extract_options.filter_param",
                    "params:vocsedici_extract_options.filter_value",
                    "voc_mariadb/node",
                    "voc_mariadb/node_field_data",
                    "voc_mariadb/paragraphs_item",
                    "voc_mariadb/paragraphs_item_field_data",
                    "voc_mariadb/paragraph__field_persona_id",
                    "voc_mariadb/paragraph__field_institucion",
                    "voc_mariadb/paragraph__field_fecha_inicio",
                    "voc_mariadb/paragraph__field_fecha_fin",
                    "voc_mariadb/node__field_nombre",
                    "voc_mariadb/node__field_apellido",
                    "voc_mariadb/node__field_orcid",
                    "voc_mariadb/node__field_mail",
                    "voc_mariadb/node__field_dni",
                    "voc_mariadb/node__field_cuit",
                    "voc_mariadb/node__field_telefono",
                    "voc_mariadb/node__field_direcci_n",
                    "voc_mariadb/node__field_google_scholar",
                    "voc_mariadb/node__field_researchgate",
                    "voc_mariadb/node__field_old_id",
                    "voc_mariadb/node__field_filiacion",
                    "voc_mariadb/node__field_nombre_institucion",
                    "voc_mariadb/node__field_nombre_institucion_variant",
                    "voc_mariadb/node__field_abreviatura",
                    "voc_mariadb/node__field_id_pidu",
                    "voc_mariadb/node__field_id_termino",
                    "voc_mariadb/node__field_padre",
                ],
                outputs=[
                    "raw/voc/node_legacy#parquet",
                    "raw/voc/node_field_data_legacy#parquet",
                    "raw/voc/paragraphs_item_legacy#parquet",
                    "raw/voc/paragraphs_item_field_data_legacy#parquet",
                    "raw/voc/paragraph__field_persona_id_legacy#parquet",
                    "raw/voc/paragraph__field_institucion_legacy#parquet",
                    "raw/voc/paragraph__field_fecha_inicio_legacy#parquet",
                    "raw/voc/paragraph__field_fecha_fin_legacy#parquet",
                    "raw/voc/node__field_nombre_legacy#parquet",
                    "raw/voc/node__field_apellido_legacy#parquet",
                    "raw/voc/node__field_orcid_legacy#parquet",
                    "raw/voc/node__field_mail_legacy#parquet",
                    "raw/voc/node__field_dni_legacy#parquet",
                    "raw/voc/node__field_cuit_legacy#parquet",
                    "raw/voc/node__field_telefono_legacy#parquet",
                    "raw/voc/node__field_direcci_n_legacy#parquet",
                    "raw/voc/node__field_google_scholar_legacy#parquet",
                    "raw/voc/node__field_researchgate_legacy#parquet",
                    "raw/voc/node__field_old_id_legacy#parquet",
                    "raw/voc/node__field_filiacion_legacy#parquet",
                    "raw/voc/node__field_nombre_institucion_legacy#parquet",
                    "raw/voc/node__field_nombre_institucion_variant_legacy#parquet",
                    "raw/voc/node__field_abreviatura_legacy#parquet",
                    "raw/voc/node__field_id_pidu_legacy#parquet",
                    "raw/voc/node__field_id_termino_legacy#parquet",
                    "raw/voc/node__field_padre_legacy#parquet",
                ],
            )
        ],
        tags="vocsedici_extract",
    )
